### ISSUE TITLE
The profiler template is not working on Symfony 4

### ISSUE THREAD

**Issue by rubiodamian** [mapado/rest-client-sdk-bundle#13]
The profiler template "@MapadoRestClientSdkBundle/Collector/rest_client_sdk.html.twig" for data collector "mapado_rest_client_sdk" does not exist.
It semms that RestClientSdkDataCollector and MapadoRestClientSdkExtension aren't configured properly

**Comment by jdeniau** [comment]
Fixed in [0.23.1](https://packagist.org/packages/mapado/rest-client-sdk-bundle#v0.23.1)

Thanks for the report

**Comment by rubiodamian** [comment]
WOW, that was quick hahahah
thanks!!
